plugins { 
    id 'java-library'
    id 'maven-publish'  
    id 'com.diffplug.spotless' version '7.0.3'
    id 'com.gradleup.shadow' version '9.1.0'
}

repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://repo.jenkins-ci.org/public/' }
        maven { url 'https://repo.gradle.org/gradle/libs-releases' }
        mavenLocal()
}

spotless {
    java {
        target "**/*.java"		  
        googleJavaFormat()
    }
} 

shadowJar {    
    mergeServiceFiles() 
    
    archiveFileName.set("${project.rootProject.name}.jar")    
    archiveClassifier.set("") 

    dependsOn ':remaped:remap'
    dependsOn ':remaped:jar'
    dependsOn ':lib:shadowJar'
    dependsOn ':lib:jar'
} 

tasks.assemble.dependsOn tasks.shadowJar
tasks.build.dependsOn tasks.shadowJar

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
	
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'])
    
    compileOnly("com.google.googlejavaformat:google-java-format:1.27.0")

    implementation files('remaped/build/libs/remaped.jar')
    implementation files('lib/build/libs/lib.jar')
}

publishing {
    publications {
        shadow(MavenPublication) { publication ->
            groupId = 'org.kodtik.innovations'
            artifactId = 'javac'
            version = '25-beta03'
            from(components.shadow)
        }        
    }
}
